#ifndef GRAMMAR_H
#define GRAMMAR_H

/*

This file was generated by the "C - Kessels engine grammar.h" template.

*/


#define GrammarCharset0CharCount 7
wchar_t GrammarCharset0[7+1] = {
  9,
  10,
  11,
  12,
  13,
  32,
  160,
  0};
#define GrammarCharset1CharCount 1
wchar_t GrammarCharset1[1+1] = {
  45,
  0};
#define GrammarCharset2CharCount 1
wchar_t GrammarCharset2[1+1] = {
  37,
  0};
#define GrammarCharset3CharCount 1
wchar_t GrammarCharset3[1+1] = {
  38,
  0};
#define GrammarCharset4CharCount 1
wchar_t GrammarCharset4[1+1] = {
  42,
  0};
#define GrammarCharset5CharCount 1
wchar_t GrammarCharset5[1+1] = {
  44,
  0};
#define GrammarCharset6CharCount 1
wchar_t GrammarCharset6[1+1] = {
  46,
  0};
#define GrammarCharset7CharCount 1
wchar_t GrammarCharset7[1+1] = {
  47,
  0};
#define GrammarCharset8CharCount 1
wchar_t GrammarCharset8[1+1] = {
  94,
  0};
#define GrammarCharset9CharCount 1
wchar_t GrammarCharset9[1+1] = {
  124,
  0};
#define GrammarCharset10CharCount 1
wchar_t GrammarCharset10[1+1] = {
  126,
  0};
#define GrammarCharset11CharCount 1
wchar_t GrammarCharset11[1+1] = {
  43,
  0};
#define GrammarCharset12CharCount 1
wchar_t GrammarCharset12[1+1] = {
  39,
  0};
#define GrammarCharset13CharCount 10
wchar_t GrammarCharset13[10+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  0};
#define GrammarCharset14CharCount 36
wchar_t GrammarCharset14[36+1] = {
  67,
  69,
  71,
  72,
  73,
  74,
  75,
  77,
  79,
  80,
  81,
  82,
  83,
  85,
  86,
  88,
  89,
  90,
  99,
  101,
  103,
  104,
  105,
  106,
  107,
  109,
  111,
  112,
  113,
  114,
  115,
  117,
  118,
  120,
  121,
  122,
  0};
#define GrammarCharset15CharCount 2
wchar_t GrammarCharset15[2+1] = {
  65,
  97,
  0};
#define GrammarCharset16CharCount 2
wchar_t GrammarCharset16[2+1] = {
  66,
  98,
  0};
#define GrammarCharset17CharCount 2
wchar_t GrammarCharset17[2+1] = {
  68,
  100,
  0};
#define GrammarCharset18CharCount 2
wchar_t GrammarCharset18[2+1] = {
  70,
  102,
  0};
#define GrammarCharset19CharCount 2
wchar_t GrammarCharset19[2+1] = {
  76,
  108,
  0};
#define GrammarCharset20CharCount 2
wchar_t GrammarCharset20[2+1] = {
  78,
  110,
  0};
#define GrammarCharset21CharCount 2
wchar_t GrammarCharset21[2+1] = {
  84,
  116,
  0};
#define GrammarCharset22CharCount 2
wchar_t GrammarCharset22[2+1] = {
  87,
  119,
  0};
#define GrammarCharset23CharCount 63
wchar_t GrammarCharset23[63+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset24CharCount 57
wchar_t GrammarCharset24[57+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  77,
  79,
  80,
  81,
  82,
  83,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  109,
  111,
  112,
  113,
  114,
  115,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset25CharCount 61
wchar_t GrammarCharset25[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset26CharCount 2
wchar_t GrammarCharset26[2+1] = {
  73,
  105,
  0};
#define GrammarCharset27CharCount 61
wchar_t GrammarCharset27[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset28CharCount 2
wchar_t GrammarCharset28[2+1] = {
  67,
  99,
  0};
#define GrammarCharset29CharCount 61
wchar_t GrammarCharset29[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset30CharCount 2
wchar_t GrammarCharset30[2+1] = {
  69,
  101,
  0};
#define GrammarCharset31CharCount 61
wchar_t GrammarCharset31[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset32CharCount 59
wchar_t GrammarCharset32[59+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset33CharCount 2
wchar_t GrammarCharset33[2+1] = {
  85,
  117,
  0};
#define GrammarCharset34CharCount 61
wchar_t GrammarCharset34[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset35CharCount 61
wchar_t GrammarCharset35[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset36CharCount 2
wchar_t GrammarCharset36[2+1] = {
  77,
  109,
  0};
#define GrammarCharset37CharCount 61
wchar_t GrammarCharset37[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset38CharCount 61
wchar_t GrammarCharset38[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset39CharCount 2
wchar_t GrammarCharset39[2+1] = {
  82,
  114,
  0};
#define GrammarCharset40CharCount 61
wchar_t GrammarCharset40[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset41CharCount 61
wchar_t GrammarCharset41[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset42CharCount 2
wchar_t GrammarCharset42[2+1] = {
  75,
  107,
  0};
#define GrammarCharset43CharCount 61
wchar_t GrammarCharset43[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset44CharCount 2
wchar_t GrammarCharset44[2+1] = {
  79,
  111,
  0};
#define GrammarCharset45CharCount 61
wchar_t GrammarCharset45[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset46CharCount 61
wchar_t GrammarCharset46[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset47CharCount 59
wchar_t GrammarCharset47[59+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  73,
  74,
  75,
  76,
  77,
  78,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  105,
  106,
  107,
  108,
  109,
  110,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset48CharCount 2
wchar_t GrammarCharset48[2+1] = {
  72,
  104,
  0};
#define GrammarCharset49CharCount 61
wchar_t GrammarCharset49[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  95,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset50CharCount 2
wchar_t GrammarCharset50[2+1] = {
  83,
  115,
  0};


/*
struct DfaEdgeStruct {
  int TargetState;
  int CharCount;
  wchar_t *CharacterSet;
  };
*/
struct DfaEdgeStruct GrammarDfaEdgeArray0[23+1] = {
  {1,GrammarCharset0CharCount,GrammarCharset0},
  {2,GrammarCharset1CharCount,GrammarCharset1},
  {3,GrammarCharset2CharCount,GrammarCharset2},
  {4,GrammarCharset3CharCount,GrammarCharset3},
  {5,GrammarCharset4CharCount,GrammarCharset4},
  {6,GrammarCharset5CharCount,GrammarCharset5},
  {7,GrammarCharset6CharCount,GrammarCharset6},
  {8,GrammarCharset7CharCount,GrammarCharset7},
  {9,GrammarCharset8CharCount,GrammarCharset8},
  {10,GrammarCharset9CharCount,GrammarCharset9},
  {11,GrammarCharset10CharCount,GrammarCharset10},
  {12,GrammarCharset11CharCount,GrammarCharset11},
  {13,GrammarCharset12CharCount,GrammarCharset12},
  {16,GrammarCharset13CharCount,GrammarCharset13},
  {17,GrammarCharset14CharCount,GrammarCharset14},
  {19,GrammarCharset15CharCount,GrammarCharset15},
  {28,GrammarCharset16CharCount,GrammarCharset16},
  {36,GrammarCharset17CharCount,GrammarCharset17},
  {41,GrammarCharset18CharCount,GrammarCharset18},
  {46,GrammarCharset19CharCount,GrammarCharset19},
  {52,GrammarCharset20CharCount,GrammarCharset20},
  {58,GrammarCharset21CharCount,GrammarCharset21},
  {64,GrammarCharset22CharCount,GrammarCharset22},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray1[1+1] = {
  {1,GrammarCharset0CharCount,GrammarCharset0},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray2[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray3[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray4[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray5[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray6[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray7[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray8[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray9[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray10[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray11[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray12[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray13[1+1] = {
  {14,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray14[1+1] = {
  {15,GrammarCharset12CharCount,GrammarCharset12},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray15[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray16[1+1] = {
  {16,GrammarCharset13CharCount,GrammarCharset13},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray17[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray18[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray19[4+1] = {
  {18,GrammarCharset24CharCount,GrammarCharset24},
  {20,GrammarCharset19CharCount,GrammarCharset19},
  {24,GrammarCharset20CharCount,GrammarCharset20},
  {26,GrammarCharset21CharCount,GrammarCharset21},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray20[2+1] = {
  {18,GrammarCharset25CharCount,GrammarCharset25},
  {21,GrammarCharset26CharCount,GrammarCharset26},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray21[2+1] = {
  {18,GrammarCharset27CharCount,GrammarCharset27},
  {22,GrammarCharset28CharCount,GrammarCharset28},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray22[2+1] = {
  {18,GrammarCharset29CharCount,GrammarCharset29},
  {23,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray23[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray24[2+1] = {
  {18,GrammarCharset31CharCount,GrammarCharset31},
  {25,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray25[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray26[2+1] = {
  {18,GrammarCharset29CharCount,GrammarCharset29},
  {27,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray27[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray28[3+1] = {
  {18,GrammarCharset32CharCount,GrammarCharset32},
  {29,GrammarCharset30CharCount,GrammarCharset30},
  {34,GrammarCharset33CharCount,GrammarCharset33},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray29[2+1] = {
  {18,GrammarCharset27CharCount,GrammarCharset27},
  {30,GrammarCharset28CharCount,GrammarCharset28},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray30[2+1] = {
  {18,GrammarCharset34CharCount,GrammarCharset34},
  {31,GrammarCharset15CharCount,GrammarCharset15},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray31[2+1] = {
  {18,GrammarCharset35CharCount,GrammarCharset35},
  {32,GrammarCharset36CharCount,GrammarCharset36},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray32[2+1] = {
  {18,GrammarCharset29CharCount,GrammarCharset29},
  {33,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray33[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray34[2+1] = {
  {18,GrammarCharset37CharCount,GrammarCharset37},
  {35,GrammarCharset21CharCount,GrammarCharset21},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray35[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray36[2+1] = {
  {18,GrammarCharset38CharCount,GrammarCharset38},
  {37,GrammarCharset39CharCount,GrammarCharset39},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray37[2+1] = {
  {18,GrammarCharset34CharCount,GrammarCharset34},
  {38,GrammarCharset15CharCount,GrammarCharset15},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray38[2+1] = {
  {18,GrammarCharset40CharCount,GrammarCharset40},
  {39,GrammarCharset20CharCount,GrammarCharset20},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray39[2+1] = {
  {18,GrammarCharset41CharCount,GrammarCharset41},
  {40,GrammarCharset42CharCount,GrammarCharset42},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray40[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray41[2+1] = {
  {18,GrammarCharset43CharCount,GrammarCharset43},
  {42,GrammarCharset44CharCount,GrammarCharset44},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray42[2+1] = {
  {18,GrammarCharset45CharCount,GrammarCharset45},
  {43,GrammarCharset33CharCount,GrammarCharset33},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray43[2+1] = {
  {18,GrammarCharset40CharCount,GrammarCharset40},
  {44,GrammarCharset20CharCount,GrammarCharset20},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray44[2+1] = {
  {18,GrammarCharset31CharCount,GrammarCharset31},
  {45,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray45[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray46[2+1] = {
  {18,GrammarCharset29CharCount,GrammarCharset29},
  {47,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray47[2+1] = {
  {18,GrammarCharset37CharCount,GrammarCharset37},
  {48,GrammarCharset21CharCount,GrammarCharset21},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray48[2+1] = {
  {18,GrammarCharset37CharCount,GrammarCharset37},
  {49,GrammarCharset21CharCount,GrammarCharset21},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray49[2+1] = {
  {18,GrammarCharset29CharCount,GrammarCharset29},
  {50,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray50[2+1] = {
  {18,GrammarCharset38CharCount,GrammarCharset38},
  {51,GrammarCharset39CharCount,GrammarCharset39},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray51[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray52[2+1] = {
  {18,GrammarCharset45CharCount,GrammarCharset45},
  {53,GrammarCharset33CharCount,GrammarCharset33},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray53[2+1] = {
  {18,GrammarCharset35CharCount,GrammarCharset35},
  {54,GrammarCharset36CharCount,GrammarCharset36},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray54[2+1] = {
  {18,GrammarCharset46CharCount,GrammarCharset46},
  {55,GrammarCharset16CharCount,GrammarCharset16},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray55[2+1] = {
  {18,GrammarCharset29CharCount,GrammarCharset29},
  {56,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray56[2+1] = {
  {18,GrammarCharset38CharCount,GrammarCharset38},
  {57,GrammarCharset39CharCount,GrammarCharset39},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray57[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray58[3+1] = {
  {18,GrammarCharset47CharCount,GrammarCharset47},
  {59,GrammarCharset48CharCount,GrammarCharset48},
  {62,GrammarCharset44CharCount,GrammarCharset44},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray59[2+1] = {
  {18,GrammarCharset29CharCount,GrammarCharset29},
  {60,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray60[2+1] = {
  {18,GrammarCharset40CharCount,GrammarCharset40},
  {61,GrammarCharset20CharCount,GrammarCharset20},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray61[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray62[2+1] = {
  {18,GrammarCharset43CharCount,GrammarCharset43},
  {63,GrammarCharset44CharCount,GrammarCharset44},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray63[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray64[2+1] = {
  {18,GrammarCharset34CharCount,GrammarCharset34},
  {65,GrammarCharset15CharCount,GrammarCharset15},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray65[2+1] = {
  {18,GrammarCharset49CharCount,GrammarCharset49},
  {66,GrammarCharset50CharCount,GrammarCharset50},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray66[1+1] = {
  {18,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};



int GrammarRuleSymbolArray0[1+1] = {
  42,
  -1};
int GrammarRuleSymbolArray1[2+1] = {
  41,
  42,
  -1};
int GrammarRuleSymbolArray2[1+1] = {
  39,
  -1};
int GrammarRuleSymbolArray3[1+1] = {
  32,
  -1};
int GrammarRuleSymbolArray4[1+1] = {
  31,
  -1};
int GrammarRuleSymbolArray5[1+1] = {
  43,
  -1};
int GrammarRuleSymbolArray6[5+1] = {
  24,
  29,
  14,
  47,
  40,
  -1};
int GrammarRuleSymbolArray7[6+1] = {
  24,
  29,
  14,
  47,
  28,
  40,
  -1};
int GrammarRuleSymbolArray8[4+1] = {
  24,
  18,
  45,
  40,
  -1};
int GrammarRuleSymbolArray9[3+1] = {
  24,
  17,
  40,
  -1};
int GrammarRuleSymbolArray10[3+1] = {
  24,
  22,
  40,
  -1};
int GrammarRuleSymbolArray11[1+1] = {
  33,
  -1};
int GrammarRuleSymbolArray12[1+1] = {
  20,
  -1};
int GrammarRuleSymbolArray13[1+1] = {
  16,
  -1};
int GrammarRuleSymbolArray14[1+1] = {
  19,
  -1};
int GrammarRuleSymbolArray15[1+1] = {
  27,
  -1};
int GrammarRuleSymbolArray16[1+1] = {
  7,
  -1};
int GrammarRuleSymbolArray17[1+1] = {
  8,
  -1};
int GrammarRuleSymbolArray18[1+1] = {
  26,
  -1};
int GrammarRuleSymbolArray19[1+1] = {
  25,
  -1};
int GrammarRuleSymbolArray20[4+1] = {
  15,
  23,
  45,
  8,
  -1};
int GrammarRuleSymbolArray21[3+1] = {
  33,
  11,
  48,
  -1};
int GrammarRuleSymbolArray22[1+1] = {
  48,
  -1};
int GrammarRuleSymbolArray23[3+1] = {
  48,
  10,
  30,
  -1};
int GrammarRuleSymbolArray24[1+1] = {
  30,
  -1};
int GrammarRuleSymbolArray25[3+1] = {
  30,
  5,
  44,
  -1};
int GrammarRuleSymbolArray26[1+1] = {
  44,
  -1};
int GrammarRuleSymbolArray27[3+1] = {
  44,
  37,
  46,
  -1};
int GrammarRuleSymbolArray28[1+1] = {
  46,
  -1};
int GrammarRuleSymbolArray29[3+1] = {
  46,
  35,
  36,
  -1};
int GrammarRuleSymbolArray30[1+1] = {
  36,
  -1};
int GrammarRuleSymbolArray31[2+1] = {
  12,
  36,
  -1};
int GrammarRuleSymbolArray32[1+1] = {
  34,
  -1};
int GrammarRuleSymbolArray33[1+1] = {
  24,
  -1};
int GrammarRuleSymbolArray34[1+1] = {
  21,
  -1};
int GrammarRuleSymbolArray35[1+1] = {
  13,
  -1};
int GrammarRuleSymbolArray36[1+1] = {
  3,
  -1};
int GrammarRuleSymbolArray37[1+1] = {
  6,
  -1};
int GrammarRuleSymbolArray38[1+1] = {
  9,
  -1};
int GrammarRuleSymbolArray39[1+1] = {
  4,
  -1};


struct ActionStruct GrammarLalrActionArray0[9+1] = {
  {15,1,1},
  {24,1,2},
  {31,3,3},
  {32,3,4},
  {38,3,5},
  {39,3,6},
  {41,3,7},
  {42,3,8},
  {43,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray1[1+1] = {
  {23,1,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray2[4+1] = {
  {17,1,11},
  {18,1,12},
  {22,1,13},
  {29,1,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray3[2+1] = {
  {15,2,4},
  {24,2,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray4[2+1] = {
  {15,2,3},
  {24,2,3},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray5[1+1] = {
  {0,4,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray6[1+1] = {
  {0,2,2},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray7[8+1] = {
  {15,1,1},
  {24,1,2},
  {31,3,3},
  {32,3,4},
  {39,3,6},
  {41,3,7},
  {42,3,15},
  {43,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray8[1+1] = {
  {0,2,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray9[2+1] = {
  {15,2,5},
  {24,2,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray10[12+1] = {
  {12,1,16},
  {20,1,17},
  {21,1,18},
  {24,1,19},
  {30,3,20},
  {33,3,21},
  {34,3,22},
  {36,3,23},
  {44,3,24},
  {45,3,25},
  {46,3,26},
  {48,3,27},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray11[6+1] = {
  {7,1,28},
  {8,1,29},
  {16,1,30},
  {19,1,31},
  {27,1,32},
  {40,3,33},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray12[12+1] = {
  {12,1,16},
  {20,1,17},
  {21,1,18},
  {24,1,19},
  {30,3,20},
  {33,3,21},
  {34,3,22},
  {36,3,23},
  {44,3,24},
  {45,3,34},
  {46,3,26},
  {48,3,27},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray13[6+1] = {
  {7,1,28},
  {8,1,29},
  {16,1,30},
  {19,1,31},
  {27,1,32},
  {40,3,35},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray14[1+1] = {
  {14,1,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray15[1+1] = {
  {0,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray16[5+1] = {
  {12,1,16},
  {21,1,18},
  {24,1,19},
  {34,3,22},
  {36,3,37},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray17[5+1] = {
  {7,2,12},
  {8,2,12},
  {16,2,12},
  {19,2,12},
  {27,2,12},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray18[13+1] = {
  {3,2,34},
  {4,2,34},
  {5,2,34},
  {6,2,34},
  {7,2,34},
  {8,2,34},
  {9,2,34},
  {10,2,34},
  {11,2,34},
  {13,2,34},
  {16,2,34},
  {19,2,34},
  {27,2,34},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray19[13+1] = {
  {3,2,33},
  {4,2,33},
  {5,2,33},
  {6,2,33},
  {7,2,33},
  {8,2,33},
  {9,2,33},
  {10,2,33},
  {11,2,33},
  {13,2,33},
  {16,2,33},
  {19,2,33},
  {27,2,33},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray20[8+1] = {
  {5,1,38},
  {7,2,24},
  {8,2,24},
  {10,2,24},
  {11,2,24},
  {16,2,24},
  {19,2,24},
  {27,2,24},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray21[6+1] = {
  {11,1,39},
  {7,2,11},
  {8,2,11},
  {16,2,11},
  {19,2,11},
  {27,2,11},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray22[13+1] = {
  {3,2,32},
  {4,2,32},
  {5,2,32},
  {6,2,32},
  {7,2,32},
  {8,2,32},
  {9,2,32},
  {10,2,32},
  {11,2,32},
  {13,2,32},
  {16,2,32},
  {19,2,32},
  {27,2,32},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray23[13+1] = {
  {3,2,30},
  {4,2,30},
  {5,2,30},
  {6,2,30},
  {7,2,30},
  {8,2,30},
  {9,2,30},
  {10,2,30},
  {11,2,30},
  {13,2,30},
  {16,2,30},
  {19,2,30},
  {27,2,30},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray24[11+1] = {
  {3,1,40},
  {13,1,41},
  {37,3,42},
  {5,2,26},
  {7,2,26},
  {8,2,26},
  {10,2,26},
  {11,2,26},
  {16,2,26},
  {19,2,26},
  {27,2,26},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray25[1+1] = {
  {8,1,43},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray26[14+1] = {
  {4,1,44},
  {6,1,45},
  {9,1,46},
  {35,3,47},
  {3,2,28},
  {5,2,28},
  {7,2,28},
  {8,2,28},
  {10,2,28},
  {11,2,28},
  {13,2,28},
  {16,2,28},
  {19,2,28},
  {27,2,28},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray27[7+1] = {
  {10,1,48},
  {7,2,22},
  {8,2,22},
  {11,2,22},
  {16,2,22},
  {19,2,22},
  {27,2,22},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray28[2+1] = {
  {15,2,16},
  {24,2,16},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray29[2+1] = {
  {15,2,17},
  {24,2,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray30[2+1] = {
  {15,2,13},
  {24,2,13},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray31[2+1] = {
  {15,2,14},
  {24,2,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray32[2+1] = {
  {15,2,15},
  {24,2,15},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray33[2+1] = {
  {15,2,9},
  {24,2,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray34[6+1] = {
  {7,1,28},
  {8,1,29},
  {16,1,30},
  {19,1,31},
  {27,1,32},
  {40,3,49},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray35[2+1] = {
  {15,2,10},
  {24,2,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray36[3+1] = {
  {25,1,50},
  {26,1,51},
  {47,3,52},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray37[13+1] = {
  {3,2,31},
  {4,2,31},
  {5,2,31},
  {6,2,31},
  {7,2,31},
  {8,2,31},
  {9,2,31},
  {10,2,31},
  {11,2,31},
  {13,2,31},
  {16,2,31},
  {19,2,31},
  {27,2,31},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray38[7+1] = {
  {12,1,16},
  {21,1,18},
  {24,1,19},
  {34,3,22},
  {36,3,23},
  {44,3,53},
  {46,3,26},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray39[9+1] = {
  {12,1,16},
  {21,1,18},
  {24,1,19},
  {30,3,20},
  {34,3,22},
  {36,3,23},
  {44,3,24},
  {46,3,26},
  {48,3,54},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray40[3+1] = {
  {12,2,36},
  {21,2,36},
  {24,2,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray41[3+1] = {
  {12,2,35},
  {21,2,35},
  {24,2,35},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray42[6+1] = {
  {12,1,16},
  {21,1,18},
  {24,1,19},
  {34,3,22},
  {36,3,23},
  {46,3,55},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray43[1+1] = {
  {0,2,20},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray44[3+1] = {
  {12,2,39},
  {21,2,39},
  {24,2,39},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray45[3+1] = {
  {12,2,37},
  {21,2,37},
  {24,2,37},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray46[3+1] = {
  {12,2,38},
  {21,2,38},
  {24,2,38},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray47[5+1] = {
  {12,1,16},
  {21,1,18},
  {24,1,19},
  {34,3,22},
  {36,3,56},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray48[8+1] = {
  {12,1,16},
  {21,1,18},
  {24,1,19},
  {30,3,57},
  {34,3,22},
  {36,3,23},
  {44,3,24},
  {46,3,26},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray49[2+1] = {
  {15,2,8},
  {24,2,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray50[6+1] = {
  {7,2,19},
  {8,2,19},
  {16,2,19},
  {19,2,19},
  {27,2,19},
  {28,2,19},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray51[6+1] = {
  {7,2,18},
  {8,2,18},
  {16,2,18},
  {19,2,18},
  {27,2,18},
  {28,2,18},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray52[7+1] = {
  {7,1,28},
  {8,1,29},
  {16,1,30},
  {19,1,31},
  {27,1,32},
  {28,1,58},
  {40,3,59},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray53[11+1] = {
  {3,1,40},
  {13,1,41},
  {37,3,42},
  {5,2,25},
  {7,2,25},
  {8,2,25},
  {10,2,25},
  {11,2,25},
  {16,2,25},
  {19,2,25},
  {27,2,25},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray54[7+1] = {
  {10,1,48},
  {7,2,21},
  {8,2,21},
  {11,2,21},
  {16,2,21},
  {19,2,21},
  {27,2,21},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray55[14+1] = {
  {4,1,44},
  {6,1,45},
  {9,1,46},
  {35,3,47},
  {3,2,27},
  {5,2,27},
  {7,2,27},
  {8,2,27},
  {10,2,27},
  {11,2,27},
  {13,2,27},
  {16,2,27},
  {19,2,27},
  {27,2,27},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray56[13+1] = {
  {3,2,29},
  {4,2,29},
  {5,2,29},
  {6,2,29},
  {7,2,29},
  {8,2,29},
  {9,2,29},
  {10,2,29},
  {11,2,29},
  {13,2,29},
  {16,2,29},
  {19,2,29},
  {27,2,29},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray57[8+1] = {
  {5,1,38},
  {7,2,23},
  {8,2,23},
  {10,2,23},
  {11,2,23},
  {16,2,23},
  {19,2,23},
  {27,2,23},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray58[6+1] = {
  {7,1,28},
  {8,1,29},
  {16,1,30},
  {19,1,31},
  {27,1,32},
  {40,3,60},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray59[2+1] = {
  {15,2,6},
  {24,2,6},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray60[2+1] = {
  {15,2,7},
  {24,2,7},
  {-1,-1,-1}};



/*
struct SymbolStruct {
  short Kind;
  wchar_t *Name;
  };
*/
struct SymbolStruct GrammarSymbolArray[49] = {
  /*  0 */   {3,L"EOF"},
  /*  1 */   {7,L"Error"},
  /*  2 */   {2,L"Whitespace"},
  /*  3 */   {1,L"-"},
  /*  4 */   {1,L"%"},
  /*  5 */   {1,L"&"},
  /*  6 */   {1,L"*"},
  /*  7 */   {1,L","},
  /*  8 */   {1,L"."},
  /*  9 */   {1,L"/"},
  /* 10 */   {1,L"^"},
  /* 11 */   {1,L"|"},
  /* 12 */   {1,L"~"},
  /* 13 */   {1,L"+"},
  /* 14 */   {1,L"a"},
  /* 15 */   {1,L"Alice"},
  /* 16 */   {1,L"and"},
  /* 17 */   {1,L"ate"},
  /* 18 */   {1,L"became"},
  /* 19 */   {1,L"but"},
  /* 20 */   {1,L"Character"},
  /* 21 */   {1,L"Constant"},
  /* 22 */   {1,L"drank"},
  /* 23 */   {1,L"found"},
  /* 24 */   {1,L"Identifier"},
  /* 25 */   {1,L"letter"},
  /* 26 */   {1,L"number"},
  /* 27 */   {1,L"then"},
  /* 28 */   {1,L"too"},
  /* 29 */   {1,L"was"},
  /* 30 */   {0,L"Ands"},
  /* 31 */   {0,L"Assignment"},
  /* 32 */   {0,L"Declaration"},
  /* 33 */   {0,L"Expr"},
  /* 34 */   {0,L"Fact"},
  /* 35 */   {0,L"Mult"},
  /* 36 */   {0,L"Nots"},
  /* 37 */   {0,L"Plus"},
  /* 38 */   {0,L"Program"},
  /* 39 */   {0,L"Return"},
  /* 40 */   {0,L"Separator"},
  /* 41 */   {0,L"Statement"},
  /* 42 */   {0,L"StatementList"},
  /* 43 */   {0,L"Step"},
  /* 44 */   {0,L"Sums"},
  /* 45 */   {0,L"Terminal"},
  /* 46 */   {0,L"Trms"},
  /* 47 */   {0,L"Type"},
  /* 48 */   {0,L"Xors"} 
  };



/*
struct DfaEdgeStruct {
  int TargetState;
  wchar_t *CharacterSet;
  };
struct DfaStateStruct {
  int AcceptSymbol;
  int EdgeCount;
  struct DfaEdgeStruct *Edges;
  };
*/
struct DfaStateStruct GrammarDfaStateArray[67+1] = {
  /* 0 */    {-1,23,GrammarDfaEdgeArray0},
  /* 1 */    {2,1,GrammarDfaEdgeArray1},
  /* 2 */    {3,0,GrammarDfaEdgeArray2},
  /* 3 */    {4,0,GrammarDfaEdgeArray3},
  /* 4 */    {5,0,GrammarDfaEdgeArray4},
  /* 5 */    {6,0,GrammarDfaEdgeArray5},
  /* 6 */    {7,0,GrammarDfaEdgeArray6},
  /* 7 */    {8,0,GrammarDfaEdgeArray7},
  /* 8 */    {9,0,GrammarDfaEdgeArray8},
  /* 9 */    {10,0,GrammarDfaEdgeArray9},
  /* 10 */    {11,0,GrammarDfaEdgeArray10},
  /* 11 */    {12,0,GrammarDfaEdgeArray11},
  /* 12 */    {13,0,GrammarDfaEdgeArray12},
  /* 13 */    {-1,1,GrammarDfaEdgeArray13},
  /* 14 */    {-1,1,GrammarDfaEdgeArray14},
  /* 15 */    {20,0,GrammarDfaEdgeArray15},
  /* 16 */    {21,1,GrammarDfaEdgeArray16},
  /* 17 */    {24,1,GrammarDfaEdgeArray17},
  /* 18 */    {24,1,GrammarDfaEdgeArray18},
  /* 19 */    {14,4,GrammarDfaEdgeArray19},
  /* 20 */    {24,2,GrammarDfaEdgeArray20},
  /* 21 */    {24,2,GrammarDfaEdgeArray21},
  /* 22 */    {24,2,GrammarDfaEdgeArray22},
  /* 23 */    {15,1,GrammarDfaEdgeArray23},
  /* 24 */    {24,2,GrammarDfaEdgeArray24},
  /* 25 */    {16,1,GrammarDfaEdgeArray25},
  /* 26 */    {24,2,GrammarDfaEdgeArray26},
  /* 27 */    {17,1,GrammarDfaEdgeArray27},
  /* 28 */    {24,3,GrammarDfaEdgeArray28},
  /* 29 */    {24,2,GrammarDfaEdgeArray29},
  /* 30 */    {24,2,GrammarDfaEdgeArray30},
  /* 31 */    {24,2,GrammarDfaEdgeArray31},
  /* 32 */    {24,2,GrammarDfaEdgeArray32},
  /* 33 */    {18,1,GrammarDfaEdgeArray33},
  /* 34 */    {24,2,GrammarDfaEdgeArray34},
  /* 35 */    {19,1,GrammarDfaEdgeArray35},
  /* 36 */    {24,2,GrammarDfaEdgeArray36},
  /* 37 */    {24,2,GrammarDfaEdgeArray37},
  /* 38 */    {24,2,GrammarDfaEdgeArray38},
  /* 39 */    {24,2,GrammarDfaEdgeArray39},
  /* 40 */    {22,1,GrammarDfaEdgeArray40},
  /* 41 */    {24,2,GrammarDfaEdgeArray41},
  /* 42 */    {24,2,GrammarDfaEdgeArray42},
  /* 43 */    {24,2,GrammarDfaEdgeArray43},
  /* 44 */    {24,2,GrammarDfaEdgeArray44},
  /* 45 */    {23,1,GrammarDfaEdgeArray45},
  /* 46 */    {24,2,GrammarDfaEdgeArray46},
  /* 47 */    {24,2,GrammarDfaEdgeArray47},
  /* 48 */    {24,2,GrammarDfaEdgeArray48},
  /* 49 */    {24,2,GrammarDfaEdgeArray49},
  /* 50 */    {24,2,GrammarDfaEdgeArray50},
  /* 51 */    {25,1,GrammarDfaEdgeArray51},
  /* 52 */    {24,2,GrammarDfaEdgeArray52},
  /* 53 */    {24,2,GrammarDfaEdgeArray53},
  /* 54 */    {24,2,GrammarDfaEdgeArray54},
  /* 55 */    {24,2,GrammarDfaEdgeArray55},
  /* 56 */    {24,2,GrammarDfaEdgeArray56},
  /* 57 */    {26,1,GrammarDfaEdgeArray57},
  /* 58 */    {24,3,GrammarDfaEdgeArray58},
  /* 59 */    {24,2,GrammarDfaEdgeArray59},
  /* 60 */    {24,2,GrammarDfaEdgeArray60},
  /* 61 */    {27,1,GrammarDfaEdgeArray61},
  /* 62 */    {24,2,GrammarDfaEdgeArray62},
  /* 63 */    {28,1,GrammarDfaEdgeArray63},
  /* 64 */    {24,2,GrammarDfaEdgeArray64},
  /* 65 */    {24,2,GrammarDfaEdgeArray65},
  /* 66 */    {29,1,GrammarDfaEdgeArray66},
  {-1,-1,NULL}};



/*
struct RuleStruct {
  int Head;
  int SymbolsCount;
  int *Symbols;
  wchar_t *Description;
  };
*/
struct RuleStruct GrammarRuleArray[40] = {
  /*  0 */   {38,1,GrammarRuleSymbolArray0,L"<Program> ::= <StatementList>"},
  /*  1 */   {42,2,GrammarRuleSymbolArray1,L"<StatementList> ::= <Statement> <StatementList>"},
  /*  2 */   {42,1,GrammarRuleSymbolArray2,L"<StatementList> ::= <Return>"},
  /*  3 */   {41,1,GrammarRuleSymbolArray3,L"<Statement> ::= <Declaration>"},
  /*  4 */   {41,1,GrammarRuleSymbolArray4,L"<Statement> ::= <Assignment>"},
  /*  5 */   {41,1,GrammarRuleSymbolArray5,L"<Statement> ::= <Step>"},
  /*  6 */   {32,5,GrammarRuleSymbolArray6,L"<Declaration> ::= Identifier was a <Type> <Separator>"},
  /*  7 */   {32,6,GrammarRuleSymbolArray7,L"<Declaration> ::= Identifier was a <Type> too <Separator>"},
  /*  8 */   {31,4,GrammarRuleSymbolArray8,L"<Assignment> ::= Identifier became <Terminal> <Separator>"},
  /*  9 */   {43,3,GrammarRuleSymbolArray9,L"<Step> ::= Identifier ate <Separator>"},
  /* 10 */   {43,3,GrammarRuleSymbolArray10,L"<Step> ::= Identifier drank <Separator>"},
  /* 11 */   {45,1,GrammarRuleSymbolArray11,L"<Terminal> ::= <Expr>"},
  /* 12 */   {45,1,GrammarRuleSymbolArray12,L"<Terminal> ::= Character"},
  /* 13 */   {40,1,GrammarRuleSymbolArray13,L"<Separator> ::= and"},
  /* 14 */   {40,1,GrammarRuleSymbolArray14,L"<Separator> ::= but"},
  /* 15 */   {40,1,GrammarRuleSymbolArray15,L"<Separator> ::= then"},
  /* 16 */   {40,1,GrammarRuleSymbolArray16,L"<Separator> ::= ','"},
  /* 17 */   {40,1,GrammarRuleSymbolArray17,L"<Separator> ::= '.'"},
  /* 18 */   {47,1,GrammarRuleSymbolArray18,L"<Type> ::= number"},
  /* 19 */   {47,1,GrammarRuleSymbolArray19,L"<Type> ::= letter"},
  /* 20 */   {39,4,GrammarRuleSymbolArray20,L"<Return> ::= Alice found <Terminal> '.'"},
  /* 21 */   {33,3,GrammarRuleSymbolArray21,L"<Expr> ::= <Expr> '|' <Xors>"},
  /* 22 */   {33,1,GrammarRuleSymbolArray22,L"<Expr> ::= <Xors>"},
  /* 23 */   {48,3,GrammarRuleSymbolArray23,L"<Xors> ::= <Xors> '^' <Ands>"},
  /* 24 */   {48,1,GrammarRuleSymbolArray24,L"<Xors> ::= <Ands>"},
  /* 25 */   {30,3,GrammarRuleSymbolArray25,L"<Ands> ::= <Ands> '&' <Sums>"},
  /* 26 */   {30,1,GrammarRuleSymbolArray26,L"<Ands> ::= <Sums>"},
  /* 27 */   {44,3,GrammarRuleSymbolArray27,L"<Sums> ::= <Sums> <Plus> <Trms>"},
  /* 28 */   {44,1,GrammarRuleSymbolArray28,L"<Sums> ::= <Trms>"},
  /* 29 */   {46,3,GrammarRuleSymbolArray29,L"<Trms> ::= <Trms> <Mult> <Nots>"},
  /* 30 */   {46,1,GrammarRuleSymbolArray30,L"<Trms> ::= <Nots>"},
  /* 31 */   {36,2,GrammarRuleSymbolArray31,L"<Nots> ::= '~' <Nots>"},
  /* 32 */   {36,1,GrammarRuleSymbolArray32,L"<Nots> ::= <Fact>"},
  /* 33 */   {34,1,GrammarRuleSymbolArray33,L"<Fact> ::= Identifier"},
  /* 34 */   {34,1,GrammarRuleSymbolArray34,L"<Fact> ::= Constant"},
  /* 35 */   {37,1,GrammarRuleSymbolArray35,L"<Plus> ::= '+'"},
  /* 36 */   {37,1,GrammarRuleSymbolArray36,L"<Plus> ::= '-'"},
  /* 37 */   {35,1,GrammarRuleSymbolArray37,L"<Mult> ::= '*'"},
  /* 38 */   {35,1,GrammarRuleSymbolArray38,L"<Mult> ::= '/'"},
  /* 39 */   {35,1,GrammarRuleSymbolArray39,L"<Mult> ::= '%'"} 
  };



/*
struct ActionStruct {
  int Entry;
  short Action;
  int Target;
  };
struct LalrStateStruct {
  int ActionCount;
  struct ActionStruct *Actions;
  };
*/
struct LalrStateStruct GrammarLalrStateArray[61+1] = {
  /* 0 */   {9,GrammarLalrActionArray0},
  /* 1 */   {1,GrammarLalrActionArray1},
  /* 2 */   {4,GrammarLalrActionArray2},
  /* 3 */   {2,GrammarLalrActionArray3},
  /* 4 */   {2,GrammarLalrActionArray4},
  /* 5 */   {1,GrammarLalrActionArray5},
  /* 6 */   {1,GrammarLalrActionArray6},
  /* 7 */   {8,GrammarLalrActionArray7},
  /* 8 */   {1,GrammarLalrActionArray8},
  /* 9 */   {2,GrammarLalrActionArray9},
  /* 10 */   {12,GrammarLalrActionArray10},
  /* 11 */   {6,GrammarLalrActionArray11},
  /* 12 */   {12,GrammarLalrActionArray12},
  /* 13 */   {6,GrammarLalrActionArray13},
  /* 14 */   {1,GrammarLalrActionArray14},
  /* 15 */   {1,GrammarLalrActionArray15},
  /* 16 */   {5,GrammarLalrActionArray16},
  /* 17 */   {5,GrammarLalrActionArray17},
  /* 18 */   {13,GrammarLalrActionArray18},
  /* 19 */   {13,GrammarLalrActionArray19},
  /* 20 */   {8,GrammarLalrActionArray20},
  /* 21 */   {6,GrammarLalrActionArray21},
  /* 22 */   {13,GrammarLalrActionArray22},
  /* 23 */   {13,GrammarLalrActionArray23},
  /* 24 */   {11,GrammarLalrActionArray24},
  /* 25 */   {1,GrammarLalrActionArray25},
  /* 26 */   {14,GrammarLalrActionArray26},
  /* 27 */   {7,GrammarLalrActionArray27},
  /* 28 */   {2,GrammarLalrActionArray28},
  /* 29 */   {2,GrammarLalrActionArray29},
  /* 30 */   {2,GrammarLalrActionArray30},
  /* 31 */   {2,GrammarLalrActionArray31},
  /* 32 */   {2,GrammarLalrActionArray32},
  /* 33 */   {2,GrammarLalrActionArray33},
  /* 34 */   {6,GrammarLalrActionArray34},
  /* 35 */   {2,GrammarLalrActionArray35},
  /* 36 */   {3,GrammarLalrActionArray36},
  /* 37 */   {13,GrammarLalrActionArray37},
  /* 38 */   {7,GrammarLalrActionArray38},
  /* 39 */   {9,GrammarLalrActionArray39},
  /* 40 */   {3,GrammarLalrActionArray40},
  /* 41 */   {3,GrammarLalrActionArray41},
  /* 42 */   {6,GrammarLalrActionArray42},
  /* 43 */   {1,GrammarLalrActionArray43},
  /* 44 */   {3,GrammarLalrActionArray44},
  /* 45 */   {3,GrammarLalrActionArray45},
  /* 46 */   {3,GrammarLalrActionArray46},
  /* 47 */   {5,GrammarLalrActionArray47},
  /* 48 */   {8,GrammarLalrActionArray48},
  /* 49 */   {2,GrammarLalrActionArray49},
  /* 50 */   {6,GrammarLalrActionArray50},
  /* 51 */   {6,GrammarLalrActionArray51},
  /* 52 */   {7,GrammarLalrActionArray52},
  /* 53 */   {11,GrammarLalrActionArray53},
  /* 54 */   {7,GrammarLalrActionArray54},
  /* 55 */   {14,GrammarLalrActionArray55},
  /* 56 */   {13,GrammarLalrActionArray56},
  /* 57 */   {8,GrammarLalrActionArray57},
  /* 58 */   {6,GrammarLalrActionArray58},
  /* 59 */   {2,GrammarLalrActionArray59},
  /* 60 */   {2,GrammarLalrActionArray60},
  {-1,NULL}};



/*
struct GrammarStruct {
  char CaseSensitive;
  int InitialSymbol;
  int InitialDfaState;
  int InitialLalrState;
  int SymbolCount;
  struct SymbolStruct *SymbolArray;
  int RuleCount;
  struct RuleStruct *RuleArray;
  int DfaStateCount;
  struct DfaStateStruct *DfaArray;
  int LalrStateCount;
  struct LalrStateStruct *LalrArray;
  };
*/
struct GrammarStruct Grammar = {
  /* CaseSensitive */      False,
  /* InitialSymbol */      38,
  /* InitialDfaState */    0,
  /* InitialLalrState */   0,
  /* SymbolCount */        49,
  /* SymbolArray */        GrammarSymbolArray,
  /* RuleCount */          40,
  /* RuleArray */          GrammarRuleArray,
  /* DfaStateCount */      67,
  /* DfaArray */           GrammarDfaStateArray,
  /* LalrStateCount */     61,
  /* LalrArray */          GrammarLalrStateArray
  };

#endif
